#!/usr/bin/env sh

# the scripting-addition must be loaded manually if
# you are running yabai on macOS Big Sur. Uncomment
# the following line to have the injection performed
# when the config is executed during startup.
#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)
#
# sudo yabai --load-sa
# yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

yabai -m config debug_output on

### define spaces
yabai -m space 1 --label main
yabai -m space 2 --label code
yabai -m space 3 --label chill

### float system preferences. Most of these just diable Yabai form resizing them.

yabai -m rule --add app="^Google Chrome$" grid=1:1:0:0:1:1 space=main

# Coding
jetbrains='^(IntelliJ IDEA|WebStorm|CLion|WebStorm|GoLand|PyCharm)$'
yabai -m rule --add app="${jetbrains}" grid=1:1:0:0:1:1 space=code manage=off
yabai -m rule --add app="^Alacritty$" space=code


# Chill
chill_apps='^(Notion|Spotify)$'
yabai -m rule --add app="${chill_apps}" grid=1:1:0:0:1:1 space=chill manage=off

# Mac
yabai -m rule --add app="^Finder$" sticky=on layer=above manage=off
yabai -m rule --add app="^Disk Utility$" sticky=on layer=above manage=off
yabai -m rule --add app="^System Information$" sticky=on layer=above manage=off
yabai -m rule --add app="^Activity Monitor$" sticky=on layer=above manage=off
yabai -m rule --add app="^System Preferences$" sticky=on layer=above manage=off

# Other
yabai -m rule --add app="^Karabiner-Elements$" sticky=on layer=above manage=off
yabai -m rule --add app="^Karabiner-EventViewer$" sticky=on layer=above manage=off
yabai -m rule --add app="^SpaceLauncher$" manage=off
yabai -m rule --add app="^Spectacle$" manage=off
yabai -m rule --add app="^zoom.us$" manage=off
yabai -m rule --add app="^Slack$" manage=off
yabai -m rule --add app="^Audio MIDI Setup$" manage=off
yabai -m rule --add app="^Photo Booth$" manage=off
yabai -m rule --add app="^MonitorControl$" manage=off
yabai -m rule --add app="^TinkerTool$" manage=off
yabai -m rule --add app="^Display Calibrator$" manage=off
yabai -m rule --add app="^Authy Desktop$" manage=off

### global settings
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off
yabai -m config window_origin_display        default
yabai -m config window_placement             second_child
yabai -m config window_topmost               off
yabai -m config window_shadow                on
yabai -m config window_opacity               off
yabai -m config window_opacity_duration      0.0
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.90
yabai -m config window_border                on
yabai -m config window_border_width          6
yabai -m config active_window_border_color   0xff41c6fa
yabai -m config normal_window_border_color   0xff555555
yabai -m config insert_feedback_color        0xffd75f5f
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap

### general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  0
yabai -m config bottom_padding               0
yabai -m config left_padding                 0
yabai -m config right_padding                0
yabai -m config window_gap                   0

echo "yabai configuration loaded.."
